# sft_inst = """
# **Role:**  
# You are an AI designed to evaluate and provide constructive feedback on action plans in a given scenario. Your primary duty is to analyze a described scene, an agent's goal, and the planned actions, then offer feedback on their feasibility, efficiency, and potential improvements.  

# **Instructions:**  
# 1. **Analyze the Scene:**  
#    - Understand the environment, objects, and constraints present in the described situation.  
#    - Identify any important details that may impact the execution of the plan.  

# 2. **Understand the Goal:**  
#    - Ensure clarity on what the agent aims to achieve.  
#    - Consider implicit sub-goals or challenges that may arise.  

# 3. **Evaluate the Planned Actions:**  
#    - Assess whether the sequence of actions logically leads to the goal.  
#    - Identify any missing, redundant, or inefficient steps.  
#    - Detect contradictions or obstacles that might prevent success.  

# 4. **Provide Feedback:**  
#    - Highlight strengths and weaknesses of the plan.  
#    - Suggest modifications to improve effectiveness, efficiency, or realism.  
#    - If the plan is flawed, propose an alternative sequence of actions.  

# **Notes:**  
# - Be specific and detailed in your analysis.  
# - Assume the agent follows logical reasoning but may overlook details.  
# - Consider real-world feasibility unless stated otherwise.  
# - If multiple solutions exist, present alternatives with trade-offs.  

# **Example Input:**  
# **Scene:** "**INVENTORY:** radio. **SCENE:** A quiet residential street at night. Several houses line the road, each with darkened windows. A streetlamp flickers intermittently at the corner. A suspicious figure lurks in the shadows near a parked car." 
# **Goal:** "**GOAL:** Investigate the suspicious figure."
# **Planned Actions:** [walk(target=\"streetlamp\"), check_status(target=\"suspicious figure\")]

# **Example Output:**  
# "The agent approached the figure cautiously, but there is no further action. May need some talks."  
# """

sft_inst = "You are an AI designed to evaluate and provide constructive feedback on action plans in a given scenario. Your primary duty is to analyze a described scene, an agent's goal, and the planned actions, then offer feedback on their feasibility, efficiency, and potential improvements."

sft_prompt = \
"""[INST] <<SYS>>\n{system_message}<</SYS>>\n
**Scene:** {scene}\n
**Goal:** {goal}\n
**Planned Actions:** {actions}\n\n
Provide feedback on the feasibility and effectiveness of the plan. [/INST]
{feedback}"""

rl_prompt = """[INST] <<SYS>>\n{system_message}<</SYS>>\n
**Scene:** {scene}\n
**Goal:** {goal}\n
**Planned Actions:** {actions}\n\n
Provide feedback on the feasibility and effectiveness of the plan. [/INST]"""

llm_prompt = """
You are an AI that generates structured JSON output for a sequence of 1-6 actions for an agent, based on the set goal. 
You need to use the description of each object on the scene to get information about the scene and decide proper actions to reach the goal.

Given the following goal: "{goal}"
The object descriptions (type, position and additional infos): "{scene}"
The latest action sequence generated by yourself (None if this is the first iteration): {actions}
The feedback on this action sequence by another LM (None if this is the first iteration): "{feedback}"

Generate a JSON response **strictly in this format**, with these following available and valid actions:
{{
    "sequence": [
        "idle(isCombat=<bool>)",
        "walk(target=\"<str>\")",
        "run(target=\"<str>\")",
        "jump()",
        "roll(direction=<int>)",
        "punch(target=\"<str>\")",
        "melee(target=\"<str>\")", ## only valid with melee weapon on hand
        "shoot(target=\"<str>\")", ## only valid with range weapon on hand
        "magic(target=\"<str>\")", ## only valid with magic weapon on hand
        "block()",
        "pickup(item=\"<str>\")",
        "consume(item=\"<str>\")",
        "talk(dialog=\"<str>\")",
        "open(item=\"<str>\")",
        "close(item=\"<str>\")",
        "check_status(target=\"<str>\")",
        "use(item=\"<str>\")" ## only valid with household equipment on hand
    ]
}}

- The "sequence" is a list containing multiple actions.
- Each item in "sequence" is function-like, which contains an action name and its parameters.
- Follows the schema, and does not include extra text.
"""
